help([[
Load environment to run EMC_verif-global on WCOSS2
]])

load(pathJoin("cray-pals", (os.getenv("cray_pals_ver") or "None")))
load(pathJoin("PrgEnv-intel", (os.getenv("PrgEnv_intel_ver") or "None")))
load(pathJoin("intel", (os.getenv("intel_ver") or "None")))
load(pathJoin("cfp", (os.getenv("cfp_ver") or "None")))
load(pathJoin("libjpeg", (os.getenv("libjpeg_ver") or "None")))
load(pathJoin("libpng", (os.getenv("libpng_ver") or "None")))
load(pathJoin("zlib", (os.getenv("zlib_ver") or "None")))
load(pathJoin("jasper", (os.getenv("jasper_ver") or "None")))
load(pathJoin("udunits", (os.getenv("udunits_ver") or "None")))
load(pathJoin("gsl", (os.getenv("gsl_ver") or "None")))
load(pathJoin("nco", (os.getenv("nco_ver") or "None")))
load(pathJoin("prod_util", (os.getenv("prod_util_ver") or "None")))
load(pathJoin("grib_util", (os.getenv("grib_util_ver") or "None")))
load(pathJoin("wgrib2", (os.getenv("wgrib2_ver") or "None")))
load(pathJoin("imagemagick", (os.getenv("imagemagick_ver") or "None")))
load(pathJoin("met", (os.getenv("met_ver") or "None")))
load(pathJoin("metplus", (os.getenv("metplus_ver") or "None")))
load(pathJoin("python", (os.getenv("python_ver") or "None")))
prepend_path("MODULEPATH", "/apps/dev/modulefiles")
load(pathJoin("ve","evs", (os.getenv("evs_ve_ver") or "None")))
prepend_path("MODULEPATH", "/apps/test/lmodules/core")
load(pathJoin("GrADS", (os.getenv("GrADS_ver") or "None")))
load(pathJoin("netcdf", (os.getenv("netcdf_ver") or "None")))
